"""Check whether the default values of every widget property match the reference screen generated by ORNL's Phoebus nightly build.

This test is intended to catch regressions in default values, which can break existing screens when phoebusgen is used to generate them.

The test loads the reference ``all_widgets.bob`` screen (one of every widget, as
Phoebus writes it) into a :class:`Screen`, then builds a second screen containing
one default-constructed instance of every widget phoebusgen supports. Every
property of every widget is then compared, including non-scalar values such as
``Font`` and ``Axis`` dataclasses.
"""

from typing import Dict, Type
import urllib.request
import urllib.error
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

from phoebusgen.v4 import Screen
from phoebusgen.v4.widgets import Widget
from phoebusgen.v4.widgets.widget import _widget_type_from_class_name

REFERENCE_URL = 'https://controlssoftware.sns.ornl.gov/css_phoebus/nightly/all_widgets.bob'

# The widget ``name`` is the only per-instance identity property the reference
# screen populates with sample data ('Arc 1', 'Label 1', ...); every other
# property is expected to match phoebusgen's defaults.
SKIP_PROPERTIES = {'name'}

# Known, accepted differences: (widget_type, property) pairs whose reference
# value intentionally does not match a default-constructed phoebusgen widget.
KNOWN_ACCEPTABLE_DIFFS = {
    ('symbol', 'tooltip'),  # Phoebus writes literal backslash-n instead of real newlines for the symbol tooltip
    ('picture', 'file'),  # reference points at a sample image file, we intentionally leave it blank.

    # For a lot of the widgets with a property that is a list of sub-elements
    # phoebus defaults to including one or more sample sub-elements. Making the
    # default an empty list in phoebusgen is more natural for scipting purposes,
    # as in most cases the user will want to populate the list with their own data.
    # For example, doing a `.append()` with a default of one sample item would result
    # in two items, which is not what the user expects.
    # The reference screen thus will not agree with phoebusgen's default for these properties,
    # but this is intentional.
    ('template', 'instances'),
    ('multi_state_led', 'states'),
    ('symbol', 'symbols'),
    ('action_button', 'actions'),
    ('choice', 'items'),
    ('combo', 'items'),
    ('radio', 'items'),
    ('stripchart', 'traces'),
    ('stripchart', 'y_axes'),
    ('xyplot', 'traces'),
    ('xyplot', 'y_axes'),
    ('navtabs', 'tabs'),
    ('tabs', 'tabs'),
}


def _fetch_reference_root() -> ET.Element:
    """Fetch and parse the reference screen, skipping the test if unavailable."""
    try:
        with urllib.request.urlopen(REFERENCE_URL, timeout=15) as response:
            data = response.read()
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        pytest.skip(f'Could not fetch reference screen {REFERENCE_URL}: {exc}')
    try:
        return ET.fromstring(data)
    except ET.ParseError as exc:  # pragma: no cover - defensive
        pytest.skip(f'Could not parse reference screen: {exc}')


def _widget_type_to_class() -> Dict[str, Type[Widget]]:
    """Map each Phoebus widget type value (e.g. ``'text_update'``) to its class."""
    mapping = {}
    for subcls in Widget.__subclasses__():
        try:
            widget_type = _widget_type_from_class_name(subcls.__name__)
        except Exception:
            continue
        mapping[widget_type.value] = subcls
    return mapping


def test_default_widget_values_match_reference(tmp_path: Path) -> None:
    reference_root = _fetch_reference_root()
    type_to_class = _widget_type_to_class()

    # Strip out widget types phoebusgen does not implement (e.g. clock,
    # digital_clock) so the reference screen can be loaded via Screen.
    for element in list(reference_root.findall('widget')):
        if element.get('type') not in type_to_class:
            reference_root.remove(element)

    reference_file = tmp_path / 'reference.bob'
    ET.ElementTree(reference_root).write(reference_file)

    # Load the filtered reference screen exactly like a user would.
    reference_screen = Screen(f_name=str(reference_file))
    reference_widgets = reference_screen.widgets
    assert reference_widgets, 'Reference screen contained no supported widgets'

    # Build a second screen with one default-constructed instance of every
    # widget type that appears in the reference.
    our_screen = Screen('phoebusgen defaults')
    our_widget_by_type: Dict[str, Widget] = {}
    for widget in reference_widgets:
        widget_type = widget.root.attrib['type']
        if widget_type in our_widget_by_type:
            continue
        our_widget = type_to_class[widget_type]()
        our_widget_by_type[widget_type] = our_widget
        our_screen.add_widget(our_widget)

    mismatches = []
    for reference_widget in reference_widgets:
        widget_type = reference_widget.root.attrib['type']
        our_widget = our_widget_by_type[widget_type]

        for prop_name in sorted(set(our_widget.get_property_names())):
            if prop_name in SKIP_PROPERTIES:
                continue
            if (widget_type, prop_name) in KNOWN_ACCEPTABLE_DIFFS:
                continue
            try:
                reference_value = getattr(reference_widget, prop_name)
                our_value = getattr(our_widget, prop_name)
            except Exception:
                continue
            if reference_value != our_value:
                mismatches.append(
                    f'{widget_type}.{prop_name}: '
                    f'reference={reference_value!r} phoebusgen={our_value!r}'
                )

    assert not mismatches, (
        'Default widget values differ from the Phoebus reference screen:\n'
        + '\n'.join(mismatches)
    )
