---

name: Type Checking
permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Type check with ty
        run: uvx ty check phoebusgen/v4 tests/v4
